apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: s66-cloud-services
build:
  artifacts:
    - image: s66-cloud-services-api
      docker:
        target: dev
      context: services/api
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: s66-cloud-services-ui
      context: services/ui
      docker:
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.tsx"
            dest: .
          - src: "src/**/*.sass"
            dest: .
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - deployments/api/templates/deployment.yaml
      - deployments/api/templates/ingress.yaml
      - deployments/api/templates/service.yaml
      - deployments/api/templates/redis.yaml
      - deployments/ui/templates/deployment.yaml
      - deployments/ui/templates/ingress.yaml
      - deployments/ui/templates/service.yaml
