apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql
spec:
  version: "8.0-v2"
  replicas: 1
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: "Delete"
  databaseSecret:
    secretName: mysql-auth 
  args:
    - --default-authentication-plugin=mysql_native_password