apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: api
        image: s66-cloud-services-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: DB_DRIVER
            value: mysql
          - name: DB_HOST
            value: mysql
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: data
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-auth
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-auth
                key: password
          - name: API_REDIS_SERVICE
            value: "api-subscriptions"
          - name: WORKER_SERVICE
            value: worker-deployment